railroadmedia/musora-content-services

babel.config.js
jest.config.js
package-lock.json
package.json
src/contentTypeConfig.js
src/index.d.ts
src/services/sanity.js
test/sanityQueryService.test.js

made import/exports work in index.ts

MA: added extra needed fields for songs

---

src/contentTypeConfig.js
src/index.d.ts
src/index.js
src/services/sanity.js

Not sure if my query for this function is up to the standard we want, so let me know if I should change this at all.

adds fetchCourseOverview function

---

src/services/sanity.js

adds a small fix for groupBy logic and adds some more data to the fetchCourseOverview response

Some small changes for MA

---

src/services/sanity.js

Somehow this method got an extra '}' again, and I changed it so that it handles additional filter fields the same way as fetchAll does, for consistency.

Updates fetchAllFilterOptions method

---

src/services/sanity.js

MA is using this to fetch in progress cards for the "continue" section. Adding the contentType to this method as an optional param helps us get the fields we need. 
Also makes the default fields var from fetchAll a global var.

Adds contentType param to fetchByRailContentId

---

src/index.d.ts
src/index.js
src/services/railcontent.js

[MWP PR](https://github.com/railroadmedia/musora-web-platform/pull/1396)

Add vimeo-data endpoint

---

README.md
test/sanityQueryService.test.js

A few small updates:
- added some notes to the README to help with setup
- commented out console logging from tests
- fixed the `.env` processing: values are always read in as strings
- changed the sorting algorithm so that it's case-sensitive and fixes the failing test

Fix failing test and update README

---

src/contentTypeConfig.js
src/services/sanity.js
test/sanityQueryService.test.js

We should have different urls for collection pages:
- artists: https://www.musora.com/drumeo/artists/Nirvana?included_fields[]=type,song
- genre: https://www.musora.com/drumeo/genres/Electronic/quick-tips
- instructor: https://www.musora.com/drumeo/coaches/todd-sucherman/31973?included_fields[]=type,Course
Added web_url_path for collection pages
Added slug in contentTypeConfig, for the contents that should have different slug on collection pages

Web_url_path on group by groq

---

src/contentTypeConfig.js
test/sanityQueryService.test.js

Live show type is missing in fetchShowsData

Live show type is missing in fetchShowsData

---

src/contentTypeConfig.js
src/services/sanity.js
test/sanityQueryService.test.js

Dynamic filter options based on content type

BE-332 filter-options

---

src/contentTypeConfig.js
src/services/railcontent.js
src/services/sanity.js
test/sanityQueryService.test.js

TP-218: Multiple filter per category; add new criteria like focus, gear, bpm

TP-218: Multiple filters per category; add new criteria like focus, gear

---

src/contentTypeConfig.js
src/services/sanity.js
test/sanityQueryService.test.js

[MWP PR](https://github.com/railroadmedia/musora-web-platform/pull/1462)

TCH-29 Add Award Fields to Challenges, add 'is_bonus_content' and 'is_always_unlocked'

---

src/contentMetaData.js
src/contentTypeConfig.js
test/sanityQueryService.test.js

Add new show type "Odd Times With Aaron Edgar" to Drumeo Shows

New show type: Odd Times With Aaron Edgar

---

src/contentMetaData.js
src/contentTypeConfig.js

Add filter by duration support
Fix Rudiment topic tabs;
Fix workout duration tabs;
Added '15+ Minutes' tab on Drumeo/Pianote/Guitareo workouts

Be 353 354 355 tabs and filter

---

src/contentTypeConfig.js
src/filterBuilder.js
src/services/sanity.js
test/sanityQueryService.test.js

[TP-277](https://musora.atlassian.net/browse/TP-277?atlOrigin=eyJpIjoiZDE2M2IyY2ViZmQ3NDNhMDg3ZTRmZmZlYTE1MDIwNjUiLCJwIjoiaiJ9): Railcontent statuses restrictions on groq

Draft content showing up in songs catalogue for non-admin users

---

src/filterBuilder.js
src/services/sanity.js
test/sanityQueryService.test.js

Fix access to documents without permisions set

Fix access to documents without permisions set

---

src/filterBuilder.js
test/sanityQueryService.test.js

- add getFutureScheduledContentsOnly on catalogues for admin and members
- fix statuses when Scheduled exists in availableContentStatuses

Fix scheduled contents display on catalogues:

---

src/contentMetaData.js
src/services/sanity.js
test/sanityQueryService.test.js

TP-300: Fix next/prev lesson on song

Fix next/prev lesson on song

---

src/contentTypeConfig.js

Fix foundation levels url

---

src/services/sanity.js

New filter option 'All' and fix live event end time buffer

New filter option 'All' and fix live event end time buffer

---

src/services/railcontent.js

Filter playlists by categories

Filter playlists by categories

---

src/services/sanity.js

[BR-104](https://musora.atlassian.net/browse/BR-104)
- Add semester-pack type to fetchAllPacks
[BR-104]: https://musora.atlassian.net/browse/BR-104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add semester-pack type to fetchAllPacks

---

src/services/sanity.js

Update fetchLiveEvent method to take into consideration the brand

Update fetchLiveEvent method to take into consideration the brand

---

src/services/contentProgress.js
src/services/dataContext.js

Issued were reported by sanity 
https://musora-media-inc.sentry.io/issues/6129740936/?environment=production&project=4505676455739392&query=release.version%3A2.6.0&referrer=issue-stream&statsPeriod=90d&stream_index=0
https://musora-media-inc.sentry.io/issues/6156601750/?environment=production&project=4505676455739392&query=release.version%3A2.6.0&referrer=issue-stream&statsPeriod=90d&stream_index=1

MA-189: added checks when reading fields to avoid undefined values crashing app

---

src/contentTypeConfig.js
src/services/sanity.js

Reesources aws upload

---

src/filterBuilder.js
src/services/sanity.js
test/sanityQueryService.test.js

[TP-841](https://musora.atlassian.net/browse/TP-841?atlOrigin=eyJpIjoiNjQ1ODBkYzAyMjJhNGJiNGIwZWJlNWE0YjU2ZWQ5ZmUiLCJwIjoiaiJ9)
- Add user access restrictions to children in groq
- Update child_count and duration based on user access restriction
- Add user access restrictions to fetchCoachLessons method
[TP-841]: https://musora.atlassian.net/browse/TP-841?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

TP-841:Fix Drafted lesson visible to students in Course and coaches area

---

src/contentMetaData.js

Add thumb for Guitareo - Q&A

---

src/services/sanity.js
test/sanityQueryService.test.js

[BR-171](https://musora.atlassian.net/browse/BR-171)
- fix artist count and display order
[BR-171]: https://musora.atlassian.net/browse/BR-171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

BR-171 artists count and display order

---

src/contentTypeConfig.js
src/services/sanity.js

[BR-106](https://musora.atlassian.net/browse/BR-106)
- update filter options to include Introductory difficulty
[BR-106]: https://musora.atlassian.net/browse/BR-106?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Filter Options Not Displaying Introductory

---

src/services/sanity.js

[BR-138](https://musora.atlassian.net/browse/BR-138?atlOrigin=eyJpIjoiNmQ3NmU4NjNiMDZkNDU2NTljZmU3MTliZmMzOTM3NTIiLCJwIjoiaiJ9)- Drumeo Play-Alongs filters & pagination issues:
Add filters in fetchPlayAlongsCount to fix pagination issue
[BR-138]: https://musora.atlassian.net/browse/BR-138?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

BR-138: Drumeo Play-Alongs filters

---

src/services/sanity.js

[TP-769](https://musora.atlassian.net/browse/TP-769?atlOrigin=eyJpIjoiZThmNGZkODI2ZDE1NDY3YTk3MWI1YTJkZjIyYzVlYjIiLCJwIjoiaiJ9):
Set default Chapter Thumbnail Images 
[TP-769]: https://musora.atlassian.net/browse/TP-769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Set default chapter thumbnail images

---

src/index.d.ts
src/index.js
src/services/forum.js
test/forum.test.js

[MU2-263](https://musora.atlassian.net/browse/MU2-263?atlOrigin=eyJpIjoiNTMxY2E0NmY0ZTc5NDQ3MDk3NGI0MWVlYzA3MjZhMTkiLCJwIjoiaiJ9)
Provide a new MCS method with dummy data
[MU2-263]: https://musora.atlassian.net/browse/MU2-263?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

New method for Active Discussions section, with dummy data

---

src/services/railcontent.js

[MU2-262](https://musora.atlassian.net/browse/MU2-262?atlOrigin=eyJpIjoiYjdjMWU0YTBmMWJlNGY2ZmIzMWI2ODU0Yzc4MGZkMzAiLCJwIjoiaiJ9)
- update fetchUserPlaylists, addItemToPlaylist and createPlaylist methods to use new endpoints
Related PR: https://github.com/railroadmedia/musora-platform-backend/pull/13
[MU2-262]: https://musora.atlassian.net/browse/MU2-262?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Use new endpoint for User Playlists

---

src/services/sanity.js
test/sanityQueryService.test.js

Option to set forcedContentId on fetchLiveEvent method - for testing

Option to set forcedContentId on fetchLiveEvent method - for testing

---

src/index.d.ts
src/index.js
src/services/userActivity.js

New method getUserActivityStats that returns dummy data

MU2-248 streak module

---

src/services/sanity.js

In the final data structure, the `video` object will be an array of elements. This PR can be finished first so that we can bundle it with other MA changes for when the breaking changes hit playalongs.
You can test this by accessing any lessons data and verifying the video loads.
Any page that uses the lesson 
/pianote/quick-tips/nocturne-in-e-flat-but-make-it-jazz-performance/416936
https://www.musora.com/drumeo/play-alongs/ccr-rock/333131

feat(BEH-341) : part1 - PlayAlong Update: coalesce video from array to flat

---

src/services/userActivity.js

[Instrument_id and category_id can have 0 value](https://github.com/railroadmedia/musora-content-services/commit/4476a88cbb5146cfe43ae4332e04f8f030c92d76)

Instrument_id and category_id can have 0 value

---

src/services/content.js

FE needs items instead of content in getScheduleContentRows response structure

Add items in getScheduleContentRows response structure

---

src/services/imageSRCBuilder.js
src/services/imageSRCVerify.js
test/imageSRCBuilder.test.js
test/imageSRCVerify.test.js

Includes functions for building and verifying image srcs.
Build appends width, height and quality to sanity URLs to reduce bandwidth
Verify checks untransformed sanity routes and direct S3 routes.

Add image src build and verify functions

---

src/services/content-org/playlists-types.js
src/services/content-org/playlists.js

https://github.com/railroadmedia/musora-platform-backend/pull/75
Tested with devendpoint

feat (BEH-439) - playlistV2 - update addItemToPlaylist endpoint

---

src/services/imageSRCBuilder.js

Apply the same fix from v1 in v2

fix: imagedelivery.net build fix

---

src/services/userActivity.js

Apparently DayJS works differently depending on the platform. Calling `isSameDate` with formatted dates works without breaking front end.

fix(T3PS-594): wrong active date mobile

---

src/services/sanity.js

brand was required, but sometimes not passed.
- makes brand as optional query param

fix: brand query param optional
