- src/services/sanity.js
Fixes for the fetchAllFilterOptions method:
1) 400'ing due to an extra '}' in the query -> removed that
2) returning undefined due to `isList` being `false` in the `fetchSanity` method. Setting this to `true` made it return results as expected.
3) The query builder did not account for some possibly undefined params, leading to incorrect fetch results. Adjusted the query builder to return empty strings where params are undefined.
> Fixes fetchAllFilterOptions query structure

- src/services/sanity.js
- test/sanityQueryService.test.js
We now have the option to pass an array of Ids to add to the groq query. The purpose of this is for progress filters, where the array of IDs would be railcontentIds that are in progress / completed, fetched from` /content/in_progress` or `/content/completed`
> Adds progressIds param to fetchAll and FetchAllFilterOptions

- test/log.js
- test/sanityQueryService.test.js
I think it's nicer to not have console logging when we run our tests, but wanted to make a quick and easy way to enable it when it's desired.
> Add a function for console logging in tests, to keep things cleaner

- src/services/sanity.js
- test/sanityQueryService.test.js
I need to cleanup this function to implement the new groupby methods for challenges (which are not included in this PR, this is a strict 1:1 refactor). It will need another refactor later to include the filterBuilder, but step by step.
**Testing**
- added a testsuite that compares the responses of the old and new method :) verify that they're strictly equal
Once this is approved, I will remove the `fetchAllOld` method and `FetchAllRefactor` testsuite.
> Refactor fetch all to use buildEnitytAndTotal method

- README.md
- src/index.d.ts
- src/index.js
- src/services/config.js
- src/services/contentLikes.js
- src/services/dataContext.js
- src/services/railcontent.js
- src/services/sanity.js
- tools/generate-index.js
As requested by @robwillems in [BE-341](https://musora.atlassian.net/browse/BE-341), this adds the ability to exclude exported functions from the generated index.js and index.d.ts files. 
I toyed around with the idea of using comment annotations instead, where you could tag a function like this
```js
/**
* @excludeFromIndex
*/
function someFunction() {
// 
}
```
but I felt like that would be more error-prone when parsing it, might complicate the generated docs (or maybe it would be better?), and would require devs to remember to do the comment and in the right way.
While I'm not crazy about relying on the array to exist in each file and for devs to update it (I would've loved to make an abstract class or something more like that if this was in a more structured language), I felt like it's …
> Add ability to exclude exports from the generated index files

- src/contentMetaData.js
Fix group by genre on quick-tips: added 'is_group_by' to Genre tab in contentMetaData
> Fix group by genre on quick-tips

- src/filterBuilder.js
- src/index.d.ts
- src/index.js
- src/services/lastUpdated.js
- src/services/railcontent.js
- src/services/sanity.js
- src/services/userPermissions.js
- test/contentLikes.test.js
- test/contentProgress.test.js
- test/initializeTests.js
- test/lastUpdated.test.js
- test/sanityQueryService.test.js
- test/userPermissions.test.js
Added some optimizations for user permissions.
Main issue is every sanity request we make a separate call after the sanity request to get the users permissions.  I changed this to triggered at the same time as the sanity request using Promise.all.
I also made it so only one promise was created so we don't create duplicate requests simultaneously (I'm not an expect with promises so I'll need some feedback for FE/MA whether or not this technique will actually work.
> Optimizations for User Permissions

- src/contentTypeConfig.js
Challenges catalogue page should now show solo challenges as solo instead of everything as community.
> TP-134 - Update is_solo_challenge field to is_solo

- src/contentMetaData.js
- test/sanityQueryService.test.js
- Provide custom url for some Drumeo shows that have different type in Sanity
- Update processMetadata method to return a new field: url. The new field is the custom url if it was defined for selected type or the type
> Add url to contentMetadata

- src/contentTypeConfig.js
[TP-421](https://musora.atlassian.net/browse/TP-421),
Packs have one child which is a pack bundle. This leads to the current state where there's a child count of 1. This solution gets the counts of the grandchildren instead.
[TP-421]: https://musora.atlassian.net/browse/TP-421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix count for pack lessons

- src/contentTypeConfig.js
- test/sanityQueryService.test.js
[TP-582](https://musora.atlassian.net/browse/TP-582)
Instead of **match**, we should use **in** for selected creativity/essential/focus/genre/lifestyle/theory/topic filters
**match** check if we have documents that contain in creativity/essential/focus/genre/lifestyle/theory/topic name the selected filter value. If we use match and filter by ‘Rock', we will receive documents with 'Pop/Rock' genre also.
**in** will check if we have documents with 'Rock' genre name only   ( e.g.: "Rock" in genre[]->name)
[TP-582]: https://musora.atlassian.net/browse/TP-582?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix filter by creativity/essential/focus/genre/lifestyle/theory/topic

- src/services/sanity.js
[TP-577](https://musora.atlassian.net/browse/TP-577) this fixes the null check on the result of fetchNextContentDataForParent before calling fetchByRailContentId. Thanks @csillaj for the suggestion
I'll be away the next two days so if approved, please go ahead and merge this.
[TP-577]: https://musora.atlassian.net/browse/TP-577?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Improved null check on next content before fetching railcontent

- test/sanityQueryService.test.js
413955 doesn't exist in the staging dataset. I found it in production as Paradiddle Chops, so I figured this was probably done against the production dataset when created. I just found Paradiddle Chops in staging and used its ID instead.
> Fix test for fetchTopLeveldrafts to use staging ID for Paradiddle Chops

- src/services/sanity.js
[TP-775](https://musora.atlassian.net/browse/TP-775)
This adds the necessary status filtering to keep unpublished content from showing up in the results of fetching related songs.
A better solution is to use the filter builder, but this was a lot faster to implement.
[TP-775]: https://musora.atlassian.net/browse/TP-775?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add status filter for fetchRelatedSongs

- src/contentTypeConfig.js
- src/services/config.js
- src/services/sanity.js
[TP-826](https://musora.atlassian.net/browse/TP-826)
Resources should be inherited from parent object and combined with document.resources object.
This will also require a MWP update for challenges and playlist items, same format but in SanityGateway, that hasn't been implemented yet.
tested to make sure Course still works: https://dev.musora.com:8443/drumeo/courses/phil-collins-drummer-first/415264
This takes just items from the document, as there is no parent object.
**Testing:** 
both of these take from the parent, the document has no resources. 
- Pack-lesson-child: https://dev.musora.com:8443/pianote/packs/classical-piano-collection/411418/gymnopedie/411435/performance-regular-tempo/411961
- Song-tutorial-child: https://dev.musora.com:8443/pianote/song-tutorials/walking-in-memphis-tut …
> TP-826 show resources on children content

- src/index.d.ts
- src/index.js
- test/contentProgress.test.js
- tools/generate-index.cjs
[BE-428](https://musora.atlassian.net/browse/BE-428?atlOrigin=eyJpIjoiMWJhNDU4Y2VjZTk5NDdlNmFiMDIwYzBiNGZmNzQ0OGYiLCJwIjoiaiJ9)
Updated the generate-index script to correctly include globalConfig in the generated index files. This resolves the issue where globalConfig was missing, ensuring page loading in the FE.
[BE-428]: https://musora.atlassian.net/browse/BE-428?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BE-428: include global config in generated index

- src/filterBuilder.js
- src/services/sanity.js
- test/sanityQueryService.test.js
previous
[TP-558](https://musora.atlassian.net/browse/TP-558)
Features:
- added functions for querying sanity to get content with quarter_removed / quarter_published
Testing
- go to sanityQueryService.test.js
- insert these functions:
- for quarter_removed:     test('fetchQuarterRemoved', async () => { const brand = 'guitareo'; const response = await fetchQuarterRemoved(brand); });
- for quarter_published:     test('fetchQuarterPublished', async () => { const brand = 'guitareo'; const response = await fetchQuarterPublished(brand); });
- add fetchQuarterRemoved and fetchQuarterPublished to the const list at the beginning of the doc
- go to Sanity content, and change the quarter_removed attribute of a guitareo song to 2025-04-01 (the next quarter date). publish.
- grab a new piece of …
> TP-558: Adding Query Functions for Quarter Removed/Quarter Published Content

- src/services/dataContext.js
- test/dataContext.test.js
I need a method to bust the local data context caches or set last updated times from external sources.
This will be used to reduce the number of requests needed in certain situations.
> Add external method for busting local cached data

- src/contentTypeConfig.js
- src/index.d.ts
- src/index.js
- src/services/content.js
- test/contentProgress.test.js
- test/initializeTests.js
[MU2-241](https://musora.atlassian.net/browse/MU2-241?atlOrigin=eyJpIjoiN2IwNWUyYWQ3NWUwNGNlNmI3YjE5ZTAyOTJjMTgxYzAiLCJwIjoiaiJ9)
- new method that call BE endpoint to obtain content rows per brand and page name. Optional can filter by a content row id, for See All buttons
- FOR YOU tab - call the new method
[MU2-241]: https://musora.atlassian.net/browse/MU2-241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MU2 241 content rows

- src/index.d.ts
- src/index.js
- src/services/config.js
- src/services/recommendations.js
[JIRA](https://musora.atlassian.net/browse/BEH-312)
[MPB PR](https://github.com/railroadmedia/musora-platform-backend/pull/14)
[MWP PR](https://github.com/railroadmedia/musora-web-platform/pull/2051)
Notes:
- I used [this](https://docs.google.com/document/d/1Acyo38JIEcTAD3HX2K1uF9ckW-bpgtBn2-FmrgtuKEg/edit?tab=t.0) as the spec sheet
- Then tested in [Postman](https://red-shadow-611407.postman.co/workspace/Team-Workspace~38bb093f-0978-4a83-8423-944a3c78fd51/folder/31092567-ebf37dbe-30b7-4f37-96d0-e2daf1c71f7e?ctx=documentation)
- then implemented a new service file in MCS
- Then tested things :dagger: 
I haven't done anything other than the most basic error handling because I don't know what kind of garbage in/garbage out we're gunna be dealing with. Hopefully everyone plays nice. 
- …
> BEh-312: Add reccommended endpoints

- src/contentTypeConfig.js
- src/index.d.ts
- src/index.js
- src/services/recommendations.js
- src/services/sanity.js
- test/initializeTests.js
- test/sanityQueryService.test.js
[JIRA](https://musora.atlassian.net/browse/BEH-313)
Design:
- i did one endponit for each module, as different content types will use different modules and I like the SPA style 
- I refactored the testsuites to have slightly better names, and added an admin version for testing content that's blocked behind admin issues for license reasons.
- Single parent types will potentially be used by FEW/MA to determine if the related lessons module should be called.
- Song types, may change names (jam-tracks don't exist yet) but that will be my problem later when I add the type
Testing:
- I did all my testing in the testsuite. 
- I added a test for each endpoint with the provided content type. I did not add a recommended test because we don't have it configured for testing and I can't be bothered …
> BEH-313: Add related lesson endpoints

- src/lib/httpHelper.js
- src/services/railcontent.js
- src/services/recommendations.js
- src/services/user/management.js
I needed to add the new set of endpoints for user management block/unblock.
Refactored the fetch handler into it's own utility file. It takes a token and baseURl now, so it can be supported by both railcontent.js and recommended.js (or any external JSON API)
I tested this in console, because I don't have a quick way to test through the FEW yet.
To do so, wrote the global config file into console like so. 
token was generated by running `api/user-management-system/v1/sessions` in postmand and pulling the tokens out.
```
globalConfig = {  
railcontentConfig: {  
token: 'pDxpLMl0xtG6hJTQC092Yw5MUKg9UKkSkl2X1ZXx',  
userId: 631736,  
//baseUrl = 'https://dev.musora.com:8443'  
},  
recommendationsConfig: {  
token: '<go grab it from the .env file',  
baseUrl: …
```
> Add report endpoints 

- src/services/sanity.js
Methods affected:
fetchArtistLessons
fetchGenreLessons
fetchMethod
fetchMethodchildren
fetchLessonContent
fetchRelatedLessons
basically everythng except `fetchByXXX` has been updated to match the contentTypeConfig setup.
> Fix- update thumbnail_url -> thumbnail

- src/index.d.ts
- src/index.js
- src/services/railcontent.js
- [(related: BEH-845)](https://musora.atlassian.net/browse/BEH-845)
- [mpb PR](https://github.com/railroadmedia/musora-platform-backend/pull/245)
- Chris: "Peter brought this up, but I feel like we should include Undo in reset progress actions to remain consistent with most user actions that affect them have the option to undo if it was a result of misclick / they changed their mind.
Unless there’s a major complication with it, we should add it to reset progress if it’s not already there on App"
- adds restore content progress endpoint to mcs
- pull MPB changes, link mcs
- use `postContentComplete(233956)` to get progress. it will show inthe content progress row.
- use `postContentRestore(233956)` to delete the content progress. the recent progress card should disappear.
- use …
> feat(BEH-845): restore content progress endpoint

- src/services/contentProgress.js
- src/services/sanity.js
Based on a conversation I had with meenu regarding guided courses
MA-US-IDX-3: Course Not Started & First Lesson Unavailable
As a learner eager to start a course
I want tapping the card to show a toast with the release date when the first lesson is locked
So that I know exactly when I can begin
Acceptance Criteria
GIVEN the course has not yet been started by me
AND the first lesson is not yet released (locked)
WHEN I tap the course card
THEN a toast appears reading “Released on May 15 at 11:00 a.m.” in my local timezone
MA/FEW needs the published_on date for children. So I added it to navigateTo, and the tab-data field. 
Testing:
http://localhost:5173/pianote/lessons/collections
I checked the lessonsTabStore value had the correct child fields . PReviously it was just thumbnail and such. …
> fix: add published on to navigate_to
